use tonic::{Request, Response, Status};
use std::sync::Arc;
use tokio::sync::Mutex;

use crate::store::Store;
use crate::node::Node;

// this module is auto-generated by tonic-build from the .proto file
pub mod kvstore {
    tonic::include_proto!("kvstore");
}

use kvstore::kv_store_server::KvStore;
use kvstore::*;

pub struct KvService {
    pub store: Arc<Store>,
    pub node: Arc<Mutex<Node>>,
}

#[tonic::async_trait]
impl KvStore for KvService {
    async fn get(&self, request: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
        let key = request.into_inner().key;
        match self.store.get(&key) {
            Some(value) => Ok(Response::new(GetResponse { value, found: true })),
            None => Ok(Response::new(GetResponse {
                value: String::new(),
                found: false,
            })),
        }
    }

    async fn put(&self, request: Request<PutRequest>) -> Result<Response<PutResponse>, Status> {
        let req = request.into_inner();
        self.store.put(req.key, req.value);
        Ok(Response::new(PutResponse { success: true }))
    }

    async fn request_vote(
        &self,
        request: Request<VoteRequest>,
    ) -> Result<Response<VoteResponse>, Status> {
        // TODO: this is where you implement leader election logic
        // compare terms, decide whether to grant vote
        let req = request.into_inner();
        let mut node = self.node.lock().await;

        let granted = if req.term > node.term {
            node.term = req.term;
            node.voted_for = Some(req.candidate_id);
            true
        } else {
            false
        };

        Ok(Response::new(VoteResponse {
            vote_granted: granted,
            term: node.term,
        }))
    }
}